"""initial schema

Revision ID: 5553d182d39d
Revises: 
Create Date: 2026-06-14 00:48:03.385391+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5553d182d39d'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('exams',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('blueprint', sa.JSON(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exam_analytics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('exam_id', sa.String(length=36), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('difficulty_heatmap', sa.JSON(), nullable=False),
    sa.Column('per_student', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exam_analytics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_analytics_exam_id'), ['exam_id'], unique=True)

    op.create_table('generated_papers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('exam_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('seed', sa.String(length=128), nullable=False),
    sa.Column('audit_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generated_papers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generated_papers_exam_id'), ['exam_id'], unique=False)
        batch_op.create_index('ix_generated_papers_exam_student', ['exam_id', 'student_id'], unique=False)

    op.create_table('exam_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('exam_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('integrity_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['paper_id'], ['generated_papers.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exam_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_sessions_exam_id'), ['exam_id'], unique=False)
        batch_op.create_index('ix_exam_sessions_exam_student', ['exam_id', 'student_id'], unique=False)

    op.create_table('questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('answer_key', sa.Text(), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=False),
    sa.Column('difficulty', sa.Float(), nullable=False),
    sa.Column('max_marks', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['generated_papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_paper_id'), ['paper_id'], unique=False)

    op.create_table('anomalies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('source_agent', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['exam_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('anomalies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_anomalies_session_id'), ['session_id'], unique=False)

    op.create_table('answers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('time_spent_ms', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('awarded_marks', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['exam_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_answers_session_id'), ['session_id'], unique=False)

    op.create_table('session_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('client_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('server_ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['exam_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_events_session_id'), ['session_id'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('anomaly_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('delivered_ws', sa.Boolean(), nullable=False),
    sa.Column('delivered_email', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['anomaly_id'], ['anomalies.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['exam_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_session_id'))

    op.drop_table('alerts')
    with op.batch_alter_table('session_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_events_session_id'))

    op.drop_table('session_events')
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_answers_session_id'))

    op.drop_table('answers')
    with op.batch_alter_table('anomalies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anomalies_session_id'))

    op.drop_table('anomalies')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_paper_id'))

    op.drop_table('questions')
    with op.batch_alter_table('exam_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_exam_sessions_exam_student')
        batch_op.drop_index(batch_op.f('ix_exam_sessions_exam_id'))

    op.drop_table('exam_sessions')
    with op.batch_alter_table('generated_papers', schema=None) as batch_op:
        batch_op.drop_index('ix_generated_papers_exam_student')
        batch_op.drop_index(batch_op.f('ix_generated_papers_exam_id'))

    op.drop_table('generated_papers')
    with op.batch_alter_table('exam_analytics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_analytics_exam_id'))

    op.drop_table('exam_analytics')
    op.drop_table('exams')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
